resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    endpoint: JFolberth
    ref: feature/terraform_aws

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
    - template: s3account_template.yml